CREATE DATABASE auth;
USE auth;

CREATE TABLE status(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(40) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE users(
	id INT NOT NULL AUTO_INCREMENT,
	first_name VARCHAR(80) NOT NULL,
	last_name VARCHAR(80) NOT NULL,
	nick_name VARCHAR(20) NOT NULL UNIQUE,
	pass VARCHAR(255) NOT NULL,
	email VARCHAR(60) NOT NULL UNIQUE,
	date_up TIMESTAMP NOT NULL,
	status_id INT DEFAULT 1,
	PRIMARY KEY (id),
	FOREIGN KEY (status_id)
	REFERENCES status (id)
	ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE services(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(40) NOT NULL UNIQUE,
	url VARCHAR(255) NOT NULL UNIQUE,
	status_id INT DEFAULT 1,
	PRIMARY KEY (id),
	FOREIGN KEY (status_id)
	REFERENCES status (id)
	ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE sessions(
	id INT NOT NULL AUTO_INCREMENT,
	device VARCHAR(150) NOT NULL,
	date TIMESTAMP NOT NULL,
	service_id INT NOT NULL,
	status_id INT NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (service_id)
	REFERENCES services (id)
	ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (status_id)
	REFERENCES status (id)
	ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE areas(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(40),
	service_id INT NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (service_id)
	REFERENCES services (id)
	ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE roles(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(40),
	status_id INT DEFAULT 1,
	PRIMARY KEY (id),
	FOREIGN KEY (status_id)
	REFERENCES status (id)
	ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE areas_roles(
	id INT NOT NULL AUTO_INCREMENT,
	area_id INT NOT NULL,
	role_id INT NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (area_id)
	REFERENCES areas (id)
	ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (role_id)
	REFERENCES roles (id)
	ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE actions(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(40) NOT NULL UNIQUE,
	PRIMARY KEY (id)
);

CREATE TABLE entities(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(80) NOT NULL UNIQUE,
	PRIMARY KEY (id)
);

CREATE TABLE permissions(
	id INT NOT NULL AUTO_INCREMENT,
	area_id INT NOT NULL,
	action_id INT NOT NULL,
	entity_id INT NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (area_id)
	REFERENCES areas (id)
	ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (action_id)
	REFERENCES actions (id)
	ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (entity_id)
	REFERENCES entities (id)
	ON DELETE RESTRICT ON UPDATE CASCADE
);
